[build]
  # Directory to change to before starting the build
  base = "client/"
  
  # Build command
  command = "npm run build"
  
  # Directory that contains the deploy-ready files
  publish = "dist"

# Redirects for single-page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"